# file: postgresql/tasks/users_privileges.yml

- name: PostgreSQL | Determine if the server is a standby
  become: yes
  become_user: "{{postgresql_admin_user}}"
  stat:
    path: '{{ postgresql_data_directory }}/recovery.conf'
  register: postgresql_user_privileges_is_standby

- name: PostgreSQL | Update the user privileges
  postgresql_user:
    name: "{{item.name}}"
    db: "{{item.db | default(omit)}}"
    port: "{{postgresql_port}}"
    priv: "{{item.priv | default(omit)}}"
    state: present
    login_host: "{{item.host | default(omit)}}"
    login_user: "{{postgresql_admin_user}}"
    role_attr_flags: "{{item.role_attr_flags | default(omit)}}"
  become: yes
  become_user: "{{postgresql_admin_user}}"
  with_items: "{{postgresql_user_privileges}}"
  when: postgresql_users|length > 0 and postgresql_user_privileges_is_standby.stat.exists == false
